---

# file to set keys for XFR authentication
- name: Create extra config for authenticated XFR request
  ansible.builtin.template:
    src: templates/auth_transfer.j2
    dest: "{{ bind_conf_dir }}/{{ auth_file }}"
    mode: 0640
    owner: root
    group: "{{ bind_group }}"
  become: true
  when: bind_dns_keys is defined and bind_dns_keys | length > 0
  tags: bind
