---
# Initialise distribution-specific variables
- name: Include all variables in global variable directory
  ansible.builtin.include_vars: "../vars/all.yaml"

- name: |
    Load a variable file based on the OS type, or a default
    if not found. Using free-form to specify the file.
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yaml'
        - '{{ ansible_distribution }}.yaml'
      paths:
        - '../vars'

- name: |
    Load a variable file based on the hostname, or a default
    if not found. Using free-form to specify the file.
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_hostname }}.yaml'
      paths:
        - '../host_vars'

- name: Update and upgrade apt
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == 'Debian'
