---
bind_zones:
  - name: 202.85.10.in-addr.arpa
    primaries:
      - 10.85.202.120
    type: primary
    allow_update:
      - "key rndc-key"
      - "key dnslab01"
    name_servers:
      - dns-01-lab.dns1.lab.
      - dns-02-lab.dns1.lab.
  - name: dns1.lab
    primaries:
      - 10.85.202.120
    type: primary
    allow_update:
      - "key rndc-key"
      - "key dnslab01"
    name_servers:
      - dns-01-lab.dns1.lab.
      - dns-02-lab.dns1.lab.
    hosts:
      - name: dns-01-lab
        ip: 10.85.202.120
      - name: dns-02-lab
        ip: 10.85.202.121
      - name: test-subdomain-1
        ip: 100.64.1.1
      - name: test-subdomain-2
        ip: 100.64.1.2
      - name: test-subdomain-3
        ip: 100.64.1.3
      - name: test-subdomain-4
        ip: 100.64.1.4
      - name: test-subdomain-5
        ip: 100.64.1.5
      - name: test-subdomain-6
        ip: 100.64.1.6
      - name: test-subdomain-7
        ip: 100.64.1.7
      - name: test-subdomain-8
        ip: 100.64.1.8
      - name: test-subdomain-9
        ip: 100.64.1.9
      - name: test-subdomain-10
        ip: 100.64.1.10
      - name: test-subdomain-11
        ip: 100.64.1.11
      - name: test-subdomain-12
        ip: 100.64.1.12
      - name: test-subdomain-13
        ip: 100.64.1.13
      - name: test-subdomain-14
        ip: 100.64.1.14
      - name: test-subdomain-15
        ip: 100.64.1.15
      - name: test-subdomain-16
        ip: 100.64.1.16
      - name: test-subdomain-17
        ip: 100.64.1.17
      - name: test-subdomain-18
        ip: 100.64.1.18
      - name: test-subdomain-19
        ip: 100.64.1.19
      - name: test-subdomain-20
        ip: 100.64.1.20

  - name: dns2.lab
    primaries:
      - 10.85.202.121
